# -*- coding: utf-8 -*-
"""Resposta_Caderno1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FPRNWhvwxNr8YUqudiZnmWyHl0yKcZ7f
"""

# @title Exercicio 1-1
print("O python é uma linguagem CaSe SeNsItIvE")
print("O python é uma linguagem sensivel a indentação (Indent Sensitive)")
print("O python é uma das linguagens mais populares em Machine Learning")
print("O Python é mais antigo que Java")
print("O Python não possui um comando para declarar variaveis")

# @title Exercicio 1-2

"""
 Eu adoraria aprender mais sobre C# e aprender mais sobre design de sites
"""

print("Estou aprendendo Python")
print("Estou aprendendo Python")
print("Estou aprendendo Python")
print("Estou aprendendo Python")
print("Estou aprendendo Python")

# @title Exercicios 1-3
print(" Esse \n Texto \n Esta \n Dividido")
print(" Tabulação ou seja \t mais tabelas \t oh nooooo")
print("Esse texto não existe \r Agora esse existe")
print(" Esse caractere esta aqui \'")
print(" Python é muito ", end="####")
print(" Não acha?")
print(" Impar "," Impar "," Impar ", sep="par")
print(" Mais", " Um", " Texto", " Dividido", sep="\n")

# @title Exercicios 1-4
print("        p \n       pri \n      print \n     printpr \n    printprin \n   printprintp \n  printprintpri \n        p \n        p ")

# @title Exercicios 1-5
nome = 10
print(type(nome))
print("nome é com o valor 10 que é um Inteiro(int)")
romulo = 45
print(type(romulo))
print("romulo com o valor 45 que é um inteiro(int)")
desligado = "sim"
print(type(desligado))
print("desligado com o texto de sim é uma string(str)")

# @title Exercicios 1-6
valor = 3.14159265358979323846
print(f"Fica melhor formatado eu acho:{valor:.2f}")

# @title Exercicios 1-7
delta = -40

if delta > 0:
 print("Maior que 0")
else:
 print("Menor que 0")

# @title Exercicios 1-8
matriz4x3 = ("[21,22,23] \n[24,25,26] \n[27,28,29] \n[30,31,32]")

print(matriz4x3)

# @title Exercicios 1-9
Global = "Essa variavel é global"
print(Global)

def sub_to_pythonistrash():
  Local = "Essa variavel é local, poggers né"
  print(Local)
  print(Global + " só que dentro da função")

sub_to_pythonistrash()